on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_VERSION: 1.0.0

jobs:
  build:
    name: Build and Cache Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          # Java distribution. See the list of supported distributions in README file
          distribution: zulu
